/* bibtex.js — Build a real .bib file from the case study's sources. */

/** Strip characters BibTeX keys may not contain. */
function _key(base, i) {
  const clean = (base || 'source').toLowerCase().replace(/[^a-z0-9]+/g, '');
  return `${clean || 'source'}${i}`;
}

function _escape(v) {
  return String(v).split('{').join('').split('}').join('').split(String.fromCharCode(92)).join('').trim();
}

/** Derive a readable publisher/site name from a URL host. */
function _siteName(url) {
  try {
    const h = new URL(url).hostname.replace(/^www\./, '');
    const parts = h.split('.');
    // Drop a leading language/subdomain (en.wikipedia.org -> wikipedia) and the TLD.
    const core = parts.length > 2 ? parts[parts.length - 2] : parts[0];
    return core.charAt(0).toUpperCase() + core.slice(1);
  } catch {
    return 'Web Source';
  }
}

/**
 * Build BibTeX entries from:
 *  - URLs the user supplied on Screen 3 (@online)
 *  - uploaded source filenames (@misc)
 *  - the REFERENCES section of the generated case, one entry per line (@misc)
 */
export function buildBibtex(formState) {
  const company = formState.step1?.companyName || 'Case Study';
  const year = formState.step1?.timePeriodTo || new Date().getFullYear();
  const entries = [];
  let n = 1;

  // 1. The generated case study itself.
  entries.push(
`@techreport{${_key(company, n++)},
  title       = {{${_escape(company)}: A Business Case Study}},
  institution = {{IFQM Bangalore, SRM Q Club}},
  year        = {${year}},
  type        = {{Business Case Study}},
  note        = {{Generated with CaseIQ}}
}`);

  // 2. User-supplied reference URLs.
  (formState.step3?.manualURLs || []).forEach(url => {
    const site = _siteName(url);
    entries.push(
`@online{${_key(site, n++)},
  title        = {{${_escape(site)} — source material on ${_escape(company)}}},
  organization = {{${_escape(site)}}},
  url          = {${_escape(url)}},
  urldate      = {${new Date().toISOString().slice(0, 10)}},
  year         = {${year}}
}`);
  });

  // 3. Uploaded documents.
  const files = [
    ...(formState.step3?.manualPDFs || []),
    ...(formState.step3?.transcriptFiles || [])
  ];
  files.forEach(f => {
    const name = (f.name || 'document').replace(/\.[^.]+$/, '');
    entries.push(
`@misc{${_key(name, n++)},
  title = {{${_escape(name)}}},
  year  = {${year}},
  note  = {{Source document supplied by the author}}
}`);
  });

  // 4. Lines from the case study's REFERENCES section, if the model wrote one.
  const text = formState.generatedCaseText || '';
  const match = text.match(/REFERENCES?\s*\n([\s\S]*)$/i);
  if (match) {
    match[1]
      .split('\n')
      .map(l => l.replace(/^[#*\-•\d.\s]+/, '').trim())
      .filter(l => l.length > 20)
      .slice(0, 40)
      .forEach(line => {
        const yearMatch = line.match(/\((\d{4})\)/);
        const author = line.split(/[,.(]/)[0].trim() || 'reference';
        entries.push(
`@misc{${_key(author, n++)},
  title = {{${_escape(line)}}},
  year  = {${yearMatch ? yearMatch[1] : year}}
}`);
      });
  }

  const header = `% BibTeX export for "${company}"
% Generated by CaseIQ — IFQM Bangalore, SRM Q Club
% ${entries.length} entries

`;
  return header + entries.join('\n\n') + '\n';
}
