/* screens/screen8-export.js */
import { formState } from '../formState.js';
import { launchConfetti } from '../utils/animations.js';
import { showScreen } from '../router.js';

let _confettiFired = false;

export function initScreen8() {
  const el = document.getElementById('screen-8');
  el.innerHTML = `
    <div class="export-wrap">
      <div class="export-watermark">CaseIQ</div>
      <div class="export-success-icon"><i data-lucide="check-circle"></i></div>
      <h1 class="export-heading">Your case study is ready.</h1>
      <p class="export-sub">Reviewed and formatted to IFQM academic publishing standards.</p>
      <div class="export-btns">
        <button class="btn-export filled" id="e8-word">
          <i data-lucide="file-text"></i> Download as Word (.docx)
        </button>
        <button class="btn-export outline" id="e8-pdf">
          <i data-lucide="file"></i> Download as PDF
        </button>
        <button class="btn-export outline" id="e8-bib">
          <i data-lucide="link"></i> Export citations (.bib)
        </button>
        <button class="btn-export outline" id="e8-teach" style="display:none">
          <i data-lucide="book-open"></i> Download teaching note (.docx)
        </button>
      </div>
      <div style="margin-top:20px;text-align:center">
        <button class="btn-link" onclick="startOver()" style="color:var(--color-text-muted);font-size:13px">Start over</button>
      </div>
      <p class="export-footer">Built for IFQM Bangalore &amp; SRM Q Club · Powered by Gemini + RAG</p>
    </div>`;

  lucide.createIcons();

  // Show teaching note button if enabled
  if (formState.step4.includeTeachingNote) {
    document.getElementById('e8-teach').style.display = 'flex';
  }

  // Confetti — once
  if (!_confettiFired) { _confettiFired = true; setTimeout(launchConfetti, 300); }

  // Download handlers
  document.getElementById('e8-word').addEventListener('click', () => {
    if (formState.generatedFileUrl) {
      const a = document.createElement('a');
      a.href     = formState.generatedFileUrl;
      a.download = formState.generatedFileName || 'case_study.docx';
      a.click();
    } else {
      _dl('docx', 'case_study');
    }
  });
  document.getElementById('e8-pdf').addEventListener('click', async () => {
    if (!formState.generatedFileName) return;
    
    try {
        const response = await fetch('http://localhost:8000/export-pdf/', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                company_name: formState.step1.companyName
            })
        });
        
        if (!response.ok) throw new Error('PDF export failed');
        
        const blob = await response.blob();
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${formState.step1.companyName}_case_study.pdf`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
    } catch (error) {
        console.error('PDF download failed:', error);
        alert('PDF export failed. Please try downloading as Word instead.');
    }
  });
  document.getElementById('e8-bib').addEventListener('click',   () => _dl('bib',  'bibliography'));
  document.getElementById('e8-teach').addEventListener('click', () => _dl('docx', 'teaching_note'));
}

function _dl(ext, prefix) {
  const co  = (formState.step1.companyName || 'output').replace(/\s+/g,'_').toLowerCase();
  const txt = `CaseIQ Export — ${formState.step1.companyName || 'Case Study'}\nGenerated by CaseIQ v4.0 · SRM Q Club\n\n[Frontend prototype — no real API called]\n`;
  const a   = document.createElement('a');
  a.href     = 'data:text/plain;charset=utf-8,' + encodeURIComponent(txt);
  a.download = `${co}_${prefix}.${ext}`;
  a.click();
}
